/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDate: typeof import('./src/components/AppDate.vue')['default']
    PostEditor: typeof import('./src/components/PostEditor.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreadList: typeof import('./src/components/ThreadList.vue')['default']
  }
}
