/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDate: typeof import('./src/components/AppDate.vue')['default']
    CategoryList: typeof import('./src/components/CategoryList.vue')['default']
    ForumList: typeof import('./src/components/ForumList.vue')['default']
    PostEditor: typeof import('./src/components/PostEditor.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreadEditor: typeof import('./src/components/ThreadEditor.vue')['default']
    ThreadList: typeof import('./src/components/ThreadList.vue')['default']
    UserPorfileCard: typeof import('./src/components/UserPorfileCard.vue')['default']
    UserProfileCardEditor: typeof import('./src/components/UserProfileCardEditor.vue')['default']
  }
}
